<?php
/**
 *
 */

namespace JPry\VVVHelper\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

abstract class AbstractInteractCommand extends Command
{
    protected function interact(InputInterface $input, OutputInterface $output)
    {
        // TODO: Change the autogenerated stub
        parent::interact($input, $output);
    }

}
