<?php
/**
 *
 */

namespace JPry\VVVHelper\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ListSites extends Command
{
    protected function configure()
    {
        // TODO: Change the autogenerated stub
        parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // TODO: Change the autogenerated stub
        parent::execute($input, $output);
    }

    protected function interact(InputInterface $input, OutputInterface $output)
    {
        // TODO: Change the autogenerated stub
        parent::interact($input, $output);
    }

}
